### ISSUE TITLE
How to make the player work with chromecast?

### ISSUE THREAD

**Issue by chrismichaelps** [webtor-io/player-sdk-js#27]
Chromecast option when playing videos is not showing.

```javascript
export let loadPlayer = async (torrent_magnet) => {
  window.webtor = window.webtor || [];
  window.webtor.push({
    id: 'player',
    magnet: torrent_magnet,
    width: '100%',
    on: function (e) {
      if (e.name == window.webtor.TORRENT_FETCHED) {
        console.log('Torrent fetched!', e.data);
      }
      if (e.name == window.webtor.TORRENT_ERROR) {
        console.log('Torrent error!');
      }
    },
    features: {
      p2pProgress: true,
      title:       true,
      settings:    true,
      fullscreen:  true,
      subtitles:   true,
      continue:    true,
      playpause:   true,
      currentTime: true,
      timeline:    true,
      duration:    true,
      volume:      true,
      chromecast:  true,
      browse:      true,
      download:    true,
    },
    i18n: {
      en: {
        common: {
          "prepare to play": "Preparing Video Stream... Please Wait...",
        },
        stat: {
          "seeding": "Seeding",
          "waiting": "Client initialization",
          "waiting for peers": "Waiting for peers",
          "from": "from",
        },
      },
    },
  });
};
```

Any implementation required to make that functionality work?

**Comment by wlasser** [comment]
Wow. You comment is make me happy as default show-example.
@vintikzzz hello. At tnis comment, i am starting thinking you are made great project with too many missunderstanding options. Please be a simple.

**Comment by Albermonte** [comment]
It works just like that, if you don't see the chromecast button maybe be because you don't have it enabled on your web browser

![image](https://user-images.githubusercontent.com/14013679/106189276-5ac21180-61a8-11eb-8609-231745882999.png)


For example, in Brave you need to have `Media Router` enabled:

![image](https://user-images.githubusercontent.com/14013679/106189424-952bae80-61a8-11eb-8dd4-743d832e2151.png)

**Comment by chrismichaelps** [comment]
I have a desktop application with `electronjs`. In that case it would have to see how internally with `electronjs` I can activate it.

**Comment by Albermonte** [comment]
Then you don't need Webtor, you can use Webtorrent that will be faster since Webtor is downloading from Webtor's servers and Webtorrent is connecting directly to the p2p network. This is a problem in the browser since browsers don't have UDP support, but in ElectronJS you can do it on the `main` side and stream it to the `renderer` side

**Comment by chrismichaelps** [comment]
Thank you, I will consider it! :)

**Comment by vintikzzz** [comment]
@Albermonte thanks for help!
@ChrisMichaelPerezSantiago in some cases users just don't want to use p2p (because of fees for torrenting in some countries).
