### ISSUE TITLE
Player bug issues on Android!

### ISSUE THREAD

**Issue by redehaka** [webtor-io/player-sdk-js#41]
Hi,
the player have bugs in Android, not show control function., probably is js mismatch.

**Comment by wlasser** [comment]
As i am remember, you are always can use you own overlay for this functions:
webtor.play/pause and other.
Just create the css layer with hide/show triggers and implement some JS code - this is much faster, rather than await.
Most of this implemented on live example:
https://webtor.io/sdk-example.html

**Comment by vintikzzz** [comment]
@redehaka could you provide more details and screenshots?

**Comment by redehaka** [comment]
It's fixed now.
